apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
  labels:
    app: cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cicd-app
          image: docker.io/viyd/cicd-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-app
  labels:
    app: cicd-app
spec:
  type: NodePort
  selector:
    app: cicd-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000