"""empty message

Revision ID: 461de817e3d2
Revises: 
Create Date: 2018-11-07 12:56:11.176634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461de817e3d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
